apiVersion: v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    nodeSelector:
        node-role.kubernetes.io/master: ""
    containers:
      - image: {{ .Values.image }}
        name: keepalived
        args:
          - --log-console
          - --dont-fork
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
          - mountPath: /etc/keepalived/
            name: conf-volume
    hostNetwork: true
    volumes:
      - configmap:
          name: keepalived-config
        name: conf-volume

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keepalived-config
  namespace: tke
data:
  keepalived.conf: |
    global_defs {
        enable_script_security
        script_user root
    }

    vrrp_script chk {
        script "/bin/bash -c 'curl -m1 -k -s https://127.0.0.1:6443/healthz -o/dev/null'"
        interval 2
        weight -10
        fall 3
        rise 1
    }

    vrrp_instance VI_1 {
        state BACKUP
        interface {{ .Values.interface }}
        virtual_router_id {{ template "generate.vrid" . }}
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass 1111
        }
        virtual_ipaddress {
            {{ .Values.vip }}
        }
        track_script {
          chk
        }
    }
