apiVersion: v1
kind: Secret
metadata:
  name: tke-platform-cluster-certs
  namespace: tke
data:
  etcd-ca.crt: |
{{ .Values.certificate.etcdCaCrt | b64enc | indent 4 }}
  etcd.crt: |
{{ .Values.certificate.etcdCrt | b64enc | indent 4 }}
  etcd.key: |
{{ .Values.certificate.etcdKey | b64enc | indent 4 }}
  front-proxy-ca.crt: |
{{ .Values.certificate.frontProxyCaCrt | b64enc | indent 4 }}
  token.csv: {{ randAlphaNum 27 | nospace | b64enc }}{{ print ",admin,1,administrator" | nospace | b64enc }}