api:
  # tke-auth-api组件在node上的对外暴露端口，默认31138
  nodePort: 31138
  replicas: 1
  image: tkestack/tke-auth-api-amd64:v1.9.0
  enableAudit: 
  # auth的重定向访问地址，包括集群服务器ip地址（必填）、tke-gateway的域名（可选）、集群高可用的VIP地址（可选）和集群的公共可访问域名（可选）
  redirectHosts:
    - 172.18.0.2
  # tke集群的租户id，默认default
  tenantID: default
  # OIDC认证方式的secret，默认自动生成
  oIDCClientSecret: 25EOZex3zmIj5glxvYfDBp79YIM
  # authentication用户名，默认为admin
  adminUsername: admin
controller:
  replicas: 1
  image: tkestack/tke-auth-controller-amd64:v1.9.0
  # tke集群的用户名，默认为admin
  adminUsername: admin
  # tke集群的密码，默认自动生成
  adminPassword: abc123
etcd:
  host: https://172.19.0.2:2379
certificate:
  etcdCaCrt: ""
  etcdCrt: ""
  etcdKey: ""
  frontProxyCaCrt: ""
  dnsNames:
  uris: 
  ipAddresses:
kubectl:
  image:
    repository: tkestack/kubectl
    tag: 1.22.7
    imagePullPolicy: IfNotPresent